version: '3'
services:
  ubuntu-test:
    container_name: ubuntu-test
    image: zys8119/ubuntu:latest
    restart: always
    command: sh ./ubuntu-install.sh
    volumes:
      # nginx服务配置
      - "./nginx/conf.d:/etc/nginx/conf.d"
      - "./nginx/sites-enabled:/etc/nginx/sites-enabled"
      # 相关日志
      - "./logs/pm2:/root/.pm2/logs/"
      - "./logs/nginx:/var/log/nginx"
