# yaml 配置实例
version: '3'
services:
  webMonitoring:
    container_name: webMonitoring
    image: node
    restart: always
    command: ["tail", "-f", "/dev/null"]
    ports:
    # web页面端口
      - "40030:80"
    # 服务端口
      - "40010:8080"
      - "40011:8081"
    # mysql端口
      - "40020:3306"
    volumes:
      # 前端资源
      - "./web:/web"
      # 服务资源
      - "./node:/node"
      # nginx服务配置
      - "./nginx:/usr/local/nginx/conf"
      # install 帮助程序
      - "./install:/install"
