# yaml 配置实例
version: '3'
services:
  ubuntu:
    container_name: ubuntu_test
    image: ubuntu
    restart: always
    command: sh ./web-monitoring-install.sh
    ports:
    # web页面端口
      - "40030:80"
    # 服务端口
      - "40010:8080"
      - "40011:8081"
    # mysql端口
      - "40020:3306"
    volumes:
      # 前端资源
      - "./web:/web"
      # 服务资源
      - "./node:/node"
      # nginx服务配置
      - "./nginx/conf.d:/etc/nginx/conf.d"
      - "./nginx/sites-enabled:/etc/nginx/sites-enabled"
      # install 帮助程序
      - "./web-monitoring-install.sh:/web-monitoring-install.sh"
