# basic usage:
# docker-compose -f docker-compose.production.yaml up -d
#
# Or with Custom env file path (using .env as default)
# docker-compose -f docker-compose.production.yaml up -d
#
# mysql can be accessed at localhost:3306


version: "3"

services:
  app:
    image: node:16.17.0-slim
    expose:
      - 40010
    working_dir: /app
    links:
      - mysql
    depends_on:
      - mysql
    volumes:
      - ./:/app
    command: >
      bash -c "npm run start"

  mysql:
    image: mysql:5.7-debian
    ports:
      - "3306:3306"
    expose:
      - 3306
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ${MYSQL_DIR:-./runtime/mysql}:/var/lib/mysql

  nginx:
    image: nginx:stable-alpine
    ports:
      - "8080:80"
      - "8443:443"
    restart: unless-stopped
    links:
      - app:app
    depends_on:
      - app
    volumes:
      # static files
      - ${STATIC_FILES_DIR:-./static}:/usr/share/nginx/html
      # config template
      - ./nginx.conf.template:/etc/nginx/templates/default.conf.template
      # logs
      - ${NGINX_LOG_DIR:-./runtime/nginx}:/var/log/nginx


